name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: gcloud-cicd-angular
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        docker build -t gcr.io/gcloud-cicd-angular/gcloud-cicd-angular-service .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/gcloud-cicd-angular/gcloud-cicd-angular-service

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy gcloud-cicd-angular-service \
          --image gcr.io/gcloud-cicd-angular/gcloud-cicd-angular-service \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated
