name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Triggers only when merged to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gcloud-cicd-angular
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/gcloud-cicd-angular/pirate-service
          gcloud run deploy pirate-service \
            --image gcr.io/gcloud-cicd-angular/pirate-service \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
